%YAML:1.0

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.1
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0.1
Viewer.ViewpointY: -10
Viewer.ViewpointZ: 0
Viewer.ViewpointF: 500
